// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	C2S_Login
	S2C_Login
	C2S_GetInfo
	S2C_GetInfo
	IntAttr
	StrAttr
	RoleDbInfo
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type PCK int32

const (
	PCK_Default_ID     PCK = 0
	PCK_C2S_Login_ID   PCK = 1
	PCK_S2C_Login_ID   PCK = 2
	PCK_C2S_GetInfo_ID PCK = 3
	PCK_S2C_GetInfo_ID PCK = 4
	PCK_MAX_ID         PCK = 100
)

var PCK_name = map[int32]string{
	0:   "Default_ID",
	1:   "C2S_Login_ID",
	2:   "S2C_Login_ID",
	3:   "C2S_GetInfo_ID",
	4:   "S2C_GetInfo_ID",
	100: "MAX_ID",
}
var PCK_value = map[string]int32{
	"Default_ID":     0,
	"C2S_Login_ID":   1,
	"S2C_Login_ID":   2,
	"C2S_GetInfo_ID": 3,
	"S2C_GetInfo_ID": 4,
	"MAX_ID":         100,
}

func (x PCK) String() string {
	return proto1.EnumName(PCK_name, int32(x))
}
func (PCK) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type C2S_Login struct {
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *C2S_Login) Reset()                    { *m = C2S_Login{} }
func (m *C2S_Login) String() string            { return proto1.CompactTextString(m) }
func (*C2S_Login) ProtoMessage()               {}
func (*C2S_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S_Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *C2S_Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type S2C_Login struct {
	Tag       int32  `protobuf:"varint,1,opt,name=tag" json:"tag,omitempty"`
	AccountId string `protobuf:"bytes,2,opt,name=AccountId,json=accountId" json:"AccountId,omitempty"`
}

func (m *S2C_Login) Reset()                    { *m = S2C_Login{} }
func (m *S2C_Login) String() string            { return proto1.CompactTextString(m) }
func (*S2C_Login) ProtoMessage()               {}
func (*S2C_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2C_Login) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *S2C_Login) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type C2S_GetInfo struct {
}

func (m *C2S_GetInfo) Reset()                    { *m = C2S_GetInfo{} }
func (m *C2S_GetInfo) String() string            { return proto1.CompactTextString(m) }
func (*C2S_GetInfo) ProtoMessage()               {}
func (*C2S_GetInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type S2C_GetInfo struct {
	Hp int32 `protobuf:"varint,1,opt,name=hp" json:"hp,omitempty"`
	Mp int32 `protobuf:"varint,2,opt,name=mp" json:"mp,omitempty"`
}

func (m *S2C_GetInfo) Reset()                    { *m = S2C_GetInfo{} }
func (m *S2C_GetInfo) String() string            { return proto1.CompactTextString(m) }
func (*S2C_GetInfo) ProtoMessage()               {}
func (*S2C_GetInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *S2C_GetInfo) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *S2C_GetInfo) GetMp() int32 {
	if m != nil {
		return m.Mp
	}
	return 0
}

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
// db
type IntAttr struct {
	K int32 `protobuf:"varint,1,opt,name=k" json:"k,omitempty"`
	V int64 `protobuf:"varint,2,opt,name=v" json:"v,omitempty"`
}

func (m *IntAttr) Reset()                    { *m = IntAttr{} }
func (m *IntAttr) String() string            { return proto1.CompactTextString(m) }
func (*IntAttr) ProtoMessage()               {}
func (*IntAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IntAttr) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *IntAttr) GetV() int64 {
	if m != nil {
		return m.V
	}
	return 0
}

type StrAttr struct {
	K int32  `protobuf:"varint,1,opt,name=k" json:"k,omitempty"`
	V string `protobuf:"bytes,2,opt,name=v" json:"v,omitempty"`
}

func (m *StrAttr) Reset()                    { *m = StrAttr{} }
func (m *StrAttr) String() string            { return proto1.CompactTextString(m) }
func (*StrAttr) ProtoMessage()               {}
func (*StrAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StrAttr) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *StrAttr) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

type RoleDbInfo struct {
	Roleid  int32      `protobuf:"varint,1,opt,name=roleid" json:"roleid,omitempty"`
	IntAttr []*IntAttr `protobuf:"bytes,2,rep,name=intAttr" json:"intAttr,omitempty"`
	StrAttr []*StrAttr `protobuf:"bytes,3,rep,name=strAttr" json:"strAttr,omitempty"`
}

func (m *RoleDbInfo) Reset()                    { *m = RoleDbInfo{} }
func (m *RoleDbInfo) String() string            { return proto1.CompactTextString(m) }
func (*RoleDbInfo) ProtoMessage()               {}
func (*RoleDbInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RoleDbInfo) GetRoleid() int32 {
	if m != nil {
		return m.Roleid
	}
	return 0
}

func (m *RoleDbInfo) GetIntAttr() []*IntAttr {
	if m != nil {
		return m.IntAttr
	}
	return nil
}

func (m *RoleDbInfo) GetStrAttr() []*StrAttr {
	if m != nil {
		return m.StrAttr
	}
	return nil
}

func init() {
	proto1.RegisterType((*C2S_Login)(nil), "proto.C2S_Login")
	proto1.RegisterType((*S2C_Login)(nil), "proto.S2C_Login")
	proto1.RegisterType((*C2S_GetInfo)(nil), "proto.C2S_GetInfo")
	proto1.RegisterType((*S2C_GetInfo)(nil), "proto.S2C_GetInfo")
	proto1.RegisterType((*IntAttr)(nil), "proto.IntAttr")
	proto1.RegisterType((*StrAttr)(nil), "proto.StrAttr")
	proto1.RegisterType((*RoleDbInfo)(nil), "proto.RoleDbInfo")
	proto1.RegisterEnum("proto.PCK", PCK_name, PCK_value)
}

func init() { proto1.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcb, 0x6b, 0xf2, 0x40,
	0x14, 0xc5, 0xbf, 0x24, 0xbe, 0xe6, 0xea, 0x17, 0xe4, 0x2e, 0x4a, 0x28, 0x5d, 0x48, 0xa0, 0x20,
	0x85, 0xba, 0xb0, 0xcb, 0xae, 0x44, 0xa1, 0x84, 0x3e, 0x90, 0x71, 0xd3, 0x9d, 0x8c, 0x3a, 0x3e,
	0xd0, 0xc9, 0x0c, 0xc9, 0x68, 0xfb, 0xe7, 0x97, 0x3b, 0x4e, 0xc4, 0x6e, 0xba, 0xca, 0x9c, 0x73,
	0x7f, 0xf7, 0xc1, 0x09, 0x30, 0x55, 0x6e, 0x06, 0xa6, 0xd0, 0x56, 0x63, 0xdd, 0x7d, 0xd2, 0x67,
	0x60, 0xe3, 0xe1, 0x6c, 0xfe, 0xa6, 0x37, 0xbb, 0x1c, 0x11, 0x6a, 0x1f, 0x42, 0xc9, 0x24, 0xe8,
	0x05, 0x7d, 0xc6, 0x6b, 0xb9, 0x50, 0x12, 0x6f, 0xa1, 0x35, 0x15, 0x65, 0xf9, 0xa5, 0x8b, 0x55,
	0x12, 0x3a, 0xbf, 0x65, 0xbc, 0xa6, 0xe6, 0xd9, 0x70, 0xec, 0x9b, 0xbb, 0x10, 0x59, 0xb1, 0x71,
	0xbd, 0x75, 0x4e, 0x4f, 0xbc, 0x03, 0x36, 0x5a, 0x2e, 0xf5, 0x31, 0xb7, 0x59, 0xd5, 0xcb, 0x44,
	0x65, 0xa4, 0xff, 0xa1, 0x4d, 0x9b, 0x5f, 0xa4, 0xcd, 0xf2, 0xb5, 0x4e, 0x1f, 0xa1, 0x4d, 0xb3,
	0xbc, 0xc4, 0x18, 0xc2, 0xad, 0xf1, 0xc3, 0xc2, 0xad, 0x21, 0xad, 0x8c, 0x1b, 0x52, 0xe7, 0xa1,
	0x32, 0xe9, 0x3d, 0x34, 0xb3, 0xdc, 0x8e, 0xac, 0x2d, 0xb0, 0x03, 0xc1, 0xde, 0x93, 0xc1, 0x9e,
	0xd4, 0xc9, 0x71, 0x11, 0x0f, 0x4e, 0x84, 0xcd, 0x6c, 0xf1, 0x17, 0xc6, 0x08, 0xfb, 0x06, 0xe0,
	0xfa, 0x20, 0x27, 0x0b, 0xb7, 0xfb, 0x06, 0x1a, 0x85, 0x3e, 0xc8, 0xdd, 0xca, 0xe3, 0x5e, 0x61,
	0x1f, 0x9a, 0xbb, 0xf3, 0xce, 0x24, 0xec, 0x45, 0xfd, 0xf6, 0x30, 0x3e, 0x67, 0x39, 0xf0, 0x97,
	0xf0, 0xaa, 0x4c, 0x64, 0x79, 0x5e, 0x9b, 0x44, 0xbf, 0x48, 0x7f, 0x0c, 0xaf, 0xca, 0x0f, 0x0a,
	0xa2, 0xe9, 0xf8, 0x15, 0x63, 0x80, 0x89, 0x5c, 0x8b, 0xe3, 0xc1, 0xce, 0xb3, 0x49, 0xf7, 0x1f,
	0x76, 0xa1, 0x73, 0xf9, 0x2d, 0xe4, 0x04, 0xe4, 0x5c, 0xb2, 0x26, 0x27, 0x44, 0x84, 0xf8, 0x2a,
	0x40, 0xf2, 0x22, 0xf2, 0xae, 0x52, 0x24, 0xaf, 0x86, 0x00, 0x8d, 0xf7, 0xd1, 0x27, 0xbd, 0x57,
	0x8b, 0x86, 0x3b, 0xe3, 0xe9, 0x27, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x3b, 0xa7, 0x3b, 0x09, 0x02,
	0x00, 0x00,
}
