// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	C2S_Login
	S2C_Login
	C2S_GetInfo
	S2C_GetInfo
	C2S_EnterRoom
	S2C_EnterRoom
	IntAttr
	StrAttr
	RoleDbInfo
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type PCK int32

const (
	PCK_Default_ID       PCK = 0
	PCK_C2S_Login_ID     PCK = 1
	PCK_S2C_Login_ID     PCK = 2
	PCK_C2S_GetInfo_ID   PCK = 3
	PCK_S2C_GetInfo_ID   PCK = 4
	PCK_C2S_EnterRoom_ID PCK = 5
	PCK_S2C_EnterRoom_ID PCK = 6
	PCK_MAX_ID           PCK = 100
)

var PCK_name = map[int32]string{
	0:   "Default_ID",
	1:   "C2S_Login_ID",
	2:   "S2C_Login_ID",
	3:   "C2S_GetInfo_ID",
	4:   "S2C_GetInfo_ID",
	5:   "C2S_EnterRoom_ID",
	6:   "S2C_EnterRoom_ID",
	100: "MAX_ID",
}
var PCK_value = map[string]int32{
	"Default_ID":       0,
	"C2S_Login_ID":     1,
	"S2C_Login_ID":     2,
	"C2S_GetInfo_ID":   3,
	"S2C_GetInfo_ID":   4,
	"C2S_EnterRoom_ID": 5,
	"S2C_EnterRoom_ID": 6,
	"MAX_ID":           100,
}

func (x PCK) String() string {
	return proto1.EnumName(PCK_name, int32(x))
}
func (PCK) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
// db
type PLAYER_ATTR int32

const (
	PLAYER_ATTR_GOLD    PLAYER_ATTR = 0
	PLAYER_ATTR_DIAMOND PLAYER_ATTR = 1
	PLAYER_ATTR_LEVEL   PLAYER_ATTR = 2
	PLAYER_ATTR_EXP     PLAYER_ATTR = 3
)

var PLAYER_ATTR_name = map[int32]string{
	0: "GOLD",
	1: "DIAMOND",
	2: "LEVEL",
	3: "EXP",
}
var PLAYER_ATTR_value = map[string]int32{
	"GOLD":    0,
	"DIAMOND": 1,
	"LEVEL":   2,
	"EXP":     3,
}

func (x PLAYER_ATTR) String() string {
	return proto1.EnumName(PLAYER_ATTR_name, int32(x))
}
func (PLAYER_ATTR) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type C2S_Login struct {
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *C2S_Login) Reset()                    { *m = C2S_Login{} }
func (m *C2S_Login) String() string            { return proto1.CompactTextString(m) }
func (*C2S_Login) ProtoMessage()               {}
func (*C2S_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S_Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *C2S_Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type S2C_Login struct {
	Tag       int32  `protobuf:"varint,1,opt,name=tag" json:"tag,omitempty"`
	AccountId string `protobuf:"bytes,2,opt,name=AccountId,json=accountId" json:"AccountId,omitempty"`
}

func (m *S2C_Login) Reset()                    { *m = S2C_Login{} }
func (m *S2C_Login) String() string            { return proto1.CompactTextString(m) }
func (*S2C_Login) ProtoMessage()               {}
func (*S2C_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2C_Login) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *S2C_Login) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type C2S_GetInfo struct {
}

func (m *C2S_GetInfo) Reset()                    { *m = C2S_GetInfo{} }
func (m *C2S_GetInfo) String() string            { return proto1.CompactTextString(m) }
func (*C2S_GetInfo) ProtoMessage()               {}
func (*C2S_GetInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type S2C_GetInfo struct {
	IntAttr []*IntAttr `protobuf:"bytes,2,rep,name=intAttr" json:"intAttr,omitempty"`
	StrAttr []*StrAttr `protobuf:"bytes,3,rep,name=strAttr" json:"strAttr,omitempty"`
}

func (m *S2C_GetInfo) Reset()                    { *m = S2C_GetInfo{} }
func (m *S2C_GetInfo) String() string            { return proto1.CompactTextString(m) }
func (*S2C_GetInfo) ProtoMessage()               {}
func (*S2C_GetInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *S2C_GetInfo) GetIntAttr() []*IntAttr {
	if m != nil {
		return m.IntAttr
	}
	return nil
}

func (m *S2C_GetInfo) GetStrAttr() []*StrAttr {
	if m != nil {
		return m.StrAttr
	}
	return nil
}

// 进入方将
type C2S_EnterRoom struct {
	RoomType int32 `protobuf:"varint,1,opt,name=roomType" json:"roomType,omitempty"`
}

func (m *C2S_EnterRoom) Reset()                    { *m = C2S_EnterRoom{} }
func (m *C2S_EnterRoom) String() string            { return proto1.CompactTextString(m) }
func (*C2S_EnterRoom) ProtoMessage()               {}
func (*C2S_EnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *C2S_EnterRoom) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

type S2C_EnterRoom struct {
	Tag    int32 `protobuf:"varint,1,opt,name=tag" json:"tag,omitempty"`
	RoomId int32 `protobuf:"varint,2,opt,name=roomId" json:"roomId,omitempty"`
}

func (m *S2C_EnterRoom) Reset()                    { *m = S2C_EnterRoom{} }
func (m *S2C_EnterRoom) String() string            { return proto1.CompactTextString(m) }
func (*S2C_EnterRoom) ProtoMessage()               {}
func (*S2C_EnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *S2C_EnterRoom) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *S2C_EnterRoom) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type IntAttr struct {
	K int32 `protobuf:"varint,1,opt,name=k" json:"k,omitempty"`
	V int64 `protobuf:"varint,2,opt,name=v" json:"v,omitempty"`
}

func (m *IntAttr) Reset()                    { *m = IntAttr{} }
func (m *IntAttr) String() string            { return proto1.CompactTextString(m) }
func (*IntAttr) ProtoMessage()               {}
func (*IntAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IntAttr) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *IntAttr) GetV() int64 {
	if m != nil {
		return m.V
	}
	return 0
}

type StrAttr struct {
	K int32  `protobuf:"varint,1,opt,name=k" json:"k,omitempty"`
	V string `protobuf:"bytes,2,opt,name=v" json:"v,omitempty"`
}

func (m *StrAttr) Reset()                    { *m = StrAttr{} }
func (m *StrAttr) String() string            { return proto1.CompactTextString(m) }
func (*StrAttr) ProtoMessage()               {}
func (*StrAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StrAttr) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *StrAttr) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

type RoleDbInfo struct {
	Roleid  int32      `protobuf:"varint,1,opt,name=roleid" json:"roleid,omitempty"`
	IntAttr []*IntAttr `protobuf:"bytes,2,rep,name=intAttr" json:"intAttr,omitempty"`
	StrAttr []*StrAttr `protobuf:"bytes,3,rep,name=strAttr" json:"strAttr,omitempty"`
}

func (m *RoleDbInfo) Reset()                    { *m = RoleDbInfo{} }
func (m *RoleDbInfo) String() string            { return proto1.CompactTextString(m) }
func (*RoleDbInfo) ProtoMessage()               {}
func (*RoleDbInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RoleDbInfo) GetRoleid() int32 {
	if m != nil {
		return m.Roleid
	}
	return 0
}

func (m *RoleDbInfo) GetIntAttr() []*IntAttr {
	if m != nil {
		return m.IntAttr
	}
	return nil
}

func (m *RoleDbInfo) GetStrAttr() []*StrAttr {
	if m != nil {
		return m.StrAttr
	}
	return nil
}

func init() {
	proto1.RegisterType((*C2S_Login)(nil), "proto.C2S_Login")
	proto1.RegisterType((*S2C_Login)(nil), "proto.S2C_Login")
	proto1.RegisterType((*C2S_GetInfo)(nil), "proto.C2S_GetInfo")
	proto1.RegisterType((*S2C_GetInfo)(nil), "proto.S2C_GetInfo")
	proto1.RegisterType((*C2S_EnterRoom)(nil), "proto.C2S_EnterRoom")
	proto1.RegisterType((*S2C_EnterRoom)(nil), "proto.S2C_EnterRoom")
	proto1.RegisterType((*IntAttr)(nil), "proto.IntAttr")
	proto1.RegisterType((*StrAttr)(nil), "proto.StrAttr")
	proto1.RegisterType((*RoleDbInfo)(nil), "proto.RoleDbInfo")
	proto1.RegisterEnum("proto.PCK", PCK_name, PCK_value)
	proto1.RegisterEnum("proto.PLAYER_ATTR", PLAYER_ATTR_name, PLAYER_ATTR_value)
}

func init() { proto1.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x5f, 0x8b, 0xda, 0x40,
	0x14, 0xc5, 0x9b, 0x4c, 0xfe, 0x98, 0x9b, 0x55, 0xc2, 0x50, 0x8a, 0x94, 0x3e, 0x2c, 0x81, 0x82,
	0x6c, 0x61, 0x1f, 0xec, 0x4b, 0x4b, 0x9f, 0x82, 0x09, 0x4b, 0x68, 0x76, 0x37, 0x8c, 0x52, 0xec,
	0x93, 0x44, 0x1d, 0x45, 0x34, 0x19, 0x49, 0x46, 0xdb, 0x7e, 0x94, 0x7e, 0xdb, 0x72, 0xc7, 0x89,
	0x55, 0x4a, 0x1f, 0xf7, 0x29, 0x73, 0x7e, 0x73, 0x6e, 0xe6, 0xdc, 0xb9, 0x03, 0x5e, 0xd9, 0xac,
	0xef, 0xf7, 0xb5, 0x90, 0x82, 0xda, 0xea, 0x13, 0x7e, 0x01, 0x6f, 0x34, 0x1c, 0xcf, 0x32, 0xb1,
	0xde, 0x54, 0x94, 0x82, 0xf5, 0x54, 0x94, 0xbc, 0x6f, 0xdc, 0x1a, 0x03, 0x8f, 0x59, 0x55, 0x51,
	0x72, 0xfa, 0x16, 0x3a, 0x79, 0xd1, 0x34, 0x3f, 0x44, 0xbd, 0xec, 0x9b, 0x8a, 0x77, 0xf6, 0x5a,
	0x63, 0xf1, 0x78, 0x38, 0xd2, 0xc5, 0x01, 0x10, 0x59, 0xac, 0x55, 0xad, 0xcd, 0x70, 0x49, 0xdf,
	0x81, 0x17, 0x2d, 0x16, 0xe2, 0x50, 0xc9, 0xb4, 0xad, 0xf5, 0x8a, 0x16, 0x84, 0x5d, 0xf0, 0xf1,
	0xe4, 0x07, 0x2e, 0xd3, 0x6a, 0x25, 0xc2, 0x02, 0x7c, 0xfc, 0x97, 0x96, 0x74, 0x00, 0xee, 0xa6,
	0x92, 0x91, 0x94, 0x75, 0xdf, 0xbc, 0x25, 0x03, 0x7f, 0xd8, 0x3b, 0xe5, 0xbe, 0x4f, 0x4f, 0x94,
	0xb5, 0xdb, 0xe8, 0x6c, 0x64, 0xad, 0x9c, 0xe4, 0xca, 0x39, 0x3e, 0x51, 0xd6, 0x6e, 0x87, 0x1f,
	0xa0, 0x8b, 0x27, 0x26, 0x95, 0xe4, 0x35, 0x13, 0xa2, 0xc4, 0xde, 0x6a, 0x21, 0xca, 0xc9, 0xaf,
	0x3d, 0xd7, 0xb9, 0xcf, 0x3a, 0xfc, 0x0c, 0x5d, 0xcc, 0xf3, 0xd7, 0xfc, 0x6f, 0x7f, 0x6f, 0xc0,
	0x41, 0xbb, 0x6e, 0xce, 0x66, 0x5a, 0x85, 0xef, 0xc1, 0xd5, 0x29, 0xe9, 0x0d, 0x18, 0x5b, 0x5d,
	0x62, 0x6c, 0x51, 0x1d, 0x95, 0x97, 0x30, 0xe3, 0x88, 0x36, 0x1d, 0xf1, 0x7f, 0x36, 0x0f, 0x6d,
	0x3f, 0x01, 0x98, 0xd8, 0xf1, 0x78, 0xae, 0xee, 0x45, 0x9d, 0xb9, 0xe3, 0x9b, 0xa5, 0xb6, 0x6b,
	0xf5, 0x12, 0xf7, 0x75, 0xf7, 0xdb, 0x00, 0x92, 0x8f, 0xbe, 0xd2, 0x1e, 0x40, 0xcc, 0x57, 0xc5,
	0x61, 0x27, 0x67, 0x69, 0x1c, 0xbc, 0xa2, 0x01, 0xdc, 0x9c, 0xdf, 0x0c, 0x12, 0x03, 0xc9, 0xf9,
	0x21, 0x20, 0x31, 0x29, 0x85, 0xde, 0xc5, 0x74, 0x91, 0x11, 0x64, 0x17, 0x23, 0x46, 0x66, 0xd1,
	0xd7, 0x10, 0x5c, 0xcd, 0x04, 0xa9, 0x8d, 0xf4, 0xea, 0xf2, 0x91, 0x3a, 0x14, 0xc0, 0x79, 0x8c,
	0xa6, 0xb8, 0x5e, 0xde, 0x7d, 0x02, 0x3f, 0xcf, 0xa2, 0xef, 0x09, 0x9b, 0x45, 0x93, 0x09, 0xa3,
	0x1d, 0xb0, 0x1e, 0x9e, 0x33, 0x0c, 0xe7, 0x83, 0x1b, 0xa7, 0xd1, 0xe3, 0xf3, 0x13, 0xe6, 0xf2,
	0xc0, 0xce, 0x92, 0x6f, 0x49, 0x16, 0x98, 0xd4, 0x05, 0x92, 0x4c, 0xf3, 0x80, 0xcc, 0x1d, 0xd5,
	0xed, 0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x45, 0xe8, 0x97, 0x20, 0x0c, 0x03, 0x00, 0x00,
}
